### ISSUE TITLE
When you guess correctly display the person's batch information after their name

### ISSUE THREAD

**Issue by botwhytho** [jasonaowen/recurse-faces#29]
This might help people beginning a batch know who's in their batch :smile:

**Comment by jasonaowen** [comment]
This will require fixing #42 , adding the batch name to the API response, and then showing the batch name in React.

The convention in RC is to show the most recent batch they've done, so that's probably what we want to do? Or maybe we should show both - ie `Full Name (Winter 2, 2017; Spring 2, 2019)`?

**Comment by brainwane** [comment]
I have been in multiple batches, so it would be great to know "which batch was this person in with me?"

And if they've been in multiple batches, I'd want to know that too.
