### ISSUE TITLE
Avoid showing people without photos

### ISSUE THREAD

**Issue by blinry** [jasonaowen/recurse-faces#37]
Could we avoid situations like this? Maybe by checking whether the image URL contains "no_photo"?

![screenshot-2019-04-02_16:03:44](https://user-images.githubusercontent.com/81277/55432601-4c315180-5561-11e9-9441-8bbec5c4f152.png)

**Comment by jasonaowen** [comment]
@blinry yes, that's an excellent idea, thank you! I just checked and it looks like there are 35 people without a photo:

```faces=> select count(*) from people where image_url like '%no_photo%';
 count 
-------
    35
(1 row)
```

I don't see anything else in the profile that would work as a filter, so I think you're right that filtering on the URL is the best option.

**Comment by jasonaowen** [comment]
I see a few implementation options.

1. Perhaps the simplest is to filter out people who do not have a photo during the daily `update-data.py` so that they are not listed in the database. This feels somehow... punitive? exclusive? Probably people who don't have photos wouldn't mind not being included in the database of a website dedicated to looking at those photos, but it still feels not great. Additionally, it means their names cannot ever be hints for people who have photos. 

2. Another option is to modify the queries to select only people that have a photo. As currently written, that'd also prevent people without photos from showing up as hints. We'd probably want to make two queries, one for the random person and another for the additional decoy people.

3. A third option is to handle it on the front end. The current API result is a set of 4 people, with the first being shown; if the first person has no photo, the front end can move on to the next. This feels like the wrong place to handle it, though...

I'm inclined towards the second option, but am totally open to discussion!
